replicaCount: 1
image:
  repository: springboot-postgres
  tag: dev
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db-postgresql.db.svc.cluster.local:5432/mydb"
  SPRING_DATASOURCE_USERNAME: "myuser"
  SPRING_DATASOURCE_PASSWORD: "mypass"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=springboot-app,service.namespace=app,service.version=0.0.1"
  OTEL_TRACES_EXPORTER: "none"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 70
  enableMemoryMetric: false