config:
  datasource:
    host: postgres-db-postgresql.db.svc.cluster.local
    user: myuser
    password: mypass
    database: mydb
service:
  port: 9187
  targetPort: 9187
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi