apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    app: cadvisor
  ports:
  - name: cadvisor-metrics
    protocol: TCP
    port: 8081
    targetPort: 8080
