receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
processors:
  batch: {}
  resource:
    attributes:
      - key: service.namespace
        action: upsert
        value: app
exporters:
  prometheusremotewrite:
    endpoint: http://mimir.monitoring.svc.cluster.local:9009/api/v1/push
    headers:
      X-Scope-OrgID: primary
  prometheus:
    endpoint: "0.0.0.0:8889"
    # Optional reduce high-cardinality exemplars
    metric_expiration: 5m
  debug:
    verbosity: detailed
  otlp:
    endpoint: "tempo.monitoring.svc.cluster.local:4317"
    tls:
      insecure: true
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheusremotewrite, prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
