apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-custom
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
  - name: http-metrics
    protocol: TCP
    port: 8082
    targetPort: 8080
