name: jmeter_only

on:
  workflow_dispatch:
    inputs:
      test_plan:
        description: 'Path to JMeter test plan (.jmx)'
        required: true
        default: 'ansible_jmeter/tests/test_db_load_only.jmx'

jobs:
  jmeter:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    env:
      JMETER_VERSION: 5.6.3
      REPORT_DIR: jmeter-report
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Java
        run: |
          if ! command -v java >/dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y openjdk-17-jre-headless
          fi
          java -version

      - name: Download Apache JMeter
        run: |
          if [ ! -d apache-jmeter-$JMETER_VERSION ]; then
            curl -sL https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz -o jmeter.tgz
            tar -xzf jmeter.tgz
          fi
          ls -1 apache-jmeter-$JMETER_VERSION/bin/jmeter || true

      - name: Run JMeter Non-GUI
        run: |
          set -e
          PLAN="${{ github.event.inputs.test_plan }}"
          rm -rf "$REPORT_DIR" || true
          mkdir -p "$REPORT_DIR"

          apache-jmeter-$JMETER_VERSION/bin/jmeter -n -t "$PLAN" \
            -l $REPORT_DIR/results.jtl -e -o $REPORT_DIR/site

      - name: Summarize & SLA
        run: |
          echo '--- SUMMARY (raw tail) ---'
          tail -n 5 $REPORT_DIR/results.jtl || true
          TOTAL=$(grep -c '<sample ' $REPORT_DIR/results.jtl || echo 0)
          ERR=$(grep -c '<sample ' $REPORT_DIR/results.jtl | awk '{print 0}')
          # Ошибки в JTL помечаются s="false" — считаем
          ERR=$(grep -c 's="false"' $REPORT_DIR/results.jtl || echo 0)
          PCT=$(awk -v e=$ERR -v t=$TOTAL 'BEGIN{ if(t==0){print 0}else{printf "%.2f", (e/t*100)} }')
          echo "Samples: $TOTAL Errors: $ERR ($PCT%)"
          test -f $REPORT_DIR/site/index.html && echo "HTML report generated" || echo "No HTML report"
          # SLA: max 5% ошибок
          if [ $(echo "$PCT > 5" | bc -l) -eq 1 ]; then
            echo "SLA FAIL: error rate > 5%" >&2; exit 1; fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            ${{ env.REPORT_DIR }}/results.jtl
            ${{ env.REPORT_DIR }}/site
