---
name: Nightly
on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Optional note for demo'
        required: false
        default: ''
  schedule:
    # Run at minute 5 of every hour (gives a few minutes after commit for GitHub to register the new schedule)
    - cron: '5 * * * *'

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "[Nightly] Placeholder workflow (demo)."
          echo "Triggered by: ${{ github.event_name }}"
          echo "Note: ${{ github.event.inputs.note }}"
