---
name: Nightly
on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Optional note for demo'
        required: false
        default: ''

jobs:
  Nightly_performance_run:
    # Use same dedicated label set as main POC workflow so the exact same runner executes it.
    # Runner must advertise ALL these labels: self-hosted, ansible, jmeter
    runs-on: [self-hosted, ansible, jmeter]
    steps:
      - name: Placeholder / Diagnostics
        run: |
          echo "[Nightly] Placeholder workflow (demo)."
          echo "Triggered by: ${{ github.event_name }}"
          echo "Note: ${{ github.event.inputs.note }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Current UTC time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          echo "Job started on runner labels: $RUNNER_LABELS"
          echo "Runner name: $RUNNER_NAME"
