---
name: Nightly
on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Optional note for demo'
        required: false
        default: ''
  schedule:
    # Original intention was :45 each hour; added a higher frequency entry for troubleshooting missed triggers.
    # GitHub cron is UTC. A schedule only becomes active after it exists on the default branch.
    # Frequent (every 15 min) run helps confirm scheduling is functioning; retain the :45 run for original semantics.
    - cron: '45 * * * *'
    - cron: '*/15 * * * *'

jobs:
  noop:
    # Use same dedicated label set as main POC workflow so the exact same runner executes it.
    # Runner must advertise ALL these labels: self-hosted, ansible, jmeter
    runs-on: [self-hosted, ansible, jmeter]
    steps:
      - name: Placeholder / Diagnostics
        run: |
          echo "[Nightly] Placeholder workflow (demo)."
          echo "Triggered by: ${{ github.event_name }}"
          echo "Note: ${{ github.event.inputs.note }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Current UTC time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          echo "Job started on runner labels: $RUNNER_LABELS"
          echo "Runner name: $RUNNER_NAME"
